### ISSUE TITLE
[Bug] CodeRenderer use <a /> component for rendering

### ISSUE THREAD

**Issue by kopax** [bootstrap-styled/rsg-components#16]
## Type

- [x] Bug

## Description

![image](https://user-images.githubusercontent.com/1866564/49718810-ccb80380-fc8d-11e8-84ed-9b0b7c3f360c.png)

We have found that https://bootstrap-styled.github.io/motion/#/JS%20documentation is having a `CodeRenderer` that render a `<a />` tag.

This is obviously incorrect and needs to be fixed.

**Comment by santaclauze** [comment]
Fixed with commit 442c4f3853c6f93cfb2b0707c8d88bc5958b1071
