### ISSUE TITLE
SectionHeading not passing proper href

### ISSUE THREAD

**Issue by santaclauze** [bootstrap-styled/rsg-components#52]
The `SectionHeading` is not always called.

In the `styleguide.ext.json`, when we generate the documentation with:
`
      "components": [
        "src/**/[A-Z]*.js",
        "src/**/[A-Z]*/index.js"
      ],
`, the `SectionHeading` is properly called and the `href` is properly passed.

However, when generated with `    {
      "name": "Introduction",
      "content": "docs/introduction.md"
    },`, `SectionHeading` is not called, only the renderer component `SectionHeadingRenderer`.

This creates an issue with building the proper `href`.

**Comment by kopax** [comment]
I don't get it.

What do you do, what do you expect, what do you have?

I have found (but maybe it needs a reconfirmation now) that `config.components` seems to be useless, and only `config.sections[].components` is.
